/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Jugador;
import Model.Persona;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/**
 *
 * @author aldai
 */
import java.awt.event.KeyEvent;
public class frmJugadores extends javax.swing.JFrame {

    /**
     * Creates new form frmJugadores
     */
    ArrayList<Jugador> jugadores;

    public frmJugadores() {
        this.jugadores = new ArrayList<>();
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("../Image/nantes.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lblcedulaJugadores = new javax.swing.JLabel();
        txtcedulajugadores = new javax.swing.JTextField();
        lblnombrejugadores = new javax.swing.JLabel();
        txtnombrejugadores = new javax.swing.JTextField();
        lblapellidojugadores = new javax.swing.JLabel();
        txtapellidojugadores = new javax.swing.JTextField();
        lblsueldojugadores = new javax.swing.JLabel();
        txtsueldojugadores = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lblpocision = new javax.swing.JLabel();
        txtpocision = new javax.swing.JTextField();
        lblestatura = new javax.swing.JLabel();
        txtestatura = new javax.swing.JTextField();
        lblpeso = new javax.swing.JLabel();
        txtpeso = new javax.swing.JTextField();
        btnregistrarjugadores = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTjugadores = new javax.swing.JTable();
        btnsalirjugadores = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Registro de Jugadores");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Basicos"));

        lblcedulaJugadores.setText("Cedula:");

        lblnombrejugadores.setText("Nombre:");

        lblapellidojugadores.setText("Apellido");

        lblsueldojugadores.setText("Sueldo:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblcedulaJugadores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtcedulajugadores, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(lblnombrejugadores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtnombrejugadores, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(lblapellidojugadores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtapellidojugadores, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(lblsueldojugadores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtsueldojugadores, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcedulaJugadores)
                    .addComponent(txtcedulajugadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblnombrejugadores)
                    .addComponent(txtnombrejugadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblapellidojugadores)
                    .addComponent(txtapellidojugadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblsueldojugadores)
                    .addComponent(txtsueldojugadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Deportivos"));

        lblpocision.setText("Pocisión:");

        lblestatura.setText("Estatura:");

        lblpeso.setText("Peso:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(lblpocision)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtpocision, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(lblestatura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtestatura, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(lblpeso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtpeso, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblpocision)
                    .addComponent(txtpocision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblestatura)
                    .addComponent(txtestatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblpeso)
                    .addComponent(txtpeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        btnregistrarjugadores.setText("REGISTRAR");
        btnregistrarjugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrarjugadoresActionPerformed(evt);
            }
        });

        jTjugadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Cedula", "Nombre", "Apellido", "Sueldo", "Pocision", "Estatura", "Peso"
            }
        ));
        jScrollPane2.setViewportView(jTjugadores);

        btnsalirjugadores.setText("SALIR");
        btnsalirjugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirjugadoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(btnregistrarjugadores)
                        .addGap(37, 37, 37)
                        .addComponent(btnsalirjugadores, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnregistrarjugadores)
                    .addComponent(btnsalirjugadores))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsalirjugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirjugadoresActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnsalirjugadoresActionPerformed

    private void btnregistrarjugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrarjugadoresActionPerformed
        agregar();
    }//GEN-LAST:event_btnregistrarjugadoresActionPerformed
    public void agregar() {
        int id = 0;
        double sueldo = 0;
        double peso = 0;
        double estatura = 0;
        String nombre = null;
        String apellidos;
        String pocision;
        Jugador juga;
        if (txtcedulajugadores.getText().equals("") || (txtnombrejugadores.getText().equals("")) || (txtapellidojugadores.getText().equals("")) || (txtsueldojugadores.getText().equals("")) || (txtpocision.getText().equals("")) || (txtestatura.getText().equals("")) || (txtpeso.getText().equals(""))) {
            JOptionPane.showMessageDialog(null, "Llene el campo vacio");
        } else {
            try {
               
                    id = Integer.parseInt(txtcedulajugadores.getText());
            } catch (Exception e) {
                
                JOptionPane.showMessageDialog(null, "Solo se aceptan datos numericos, verifique el campo Cedula");
                return;
            }
            
            nombre = txtnombrejugadores.getText();
            apellidos = txtapellidojugadores.getText();
            try {
                sueldo = Double.parseDouble(txtsueldojugadores.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Solo se aceptan datos numericos, verifique el campo Sueldo");
                return;
            }
            pocision = txtpocision.getText();
            try {
                estatura = Double.parseDouble(txtestatura.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Solo se aceptan datos numericos, verifique el campo Estatura");
                return;
            }
            try {
                peso = Double.parseDouble(txtpeso.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Solo se aceptan datos numericos, verifique el campo Peso");
                return;
            }
            Jugador jug = new Jugador(pocision, estatura, peso, id, nombre, apellidos, sueldo);
            
            jugadores.add(jug);

            JOptionPane.showMessageDialog(null, "Datos Agregados Correctamente");
            txtcedulajugadores.setText("");
            txtnombrejugadores.setText("");
            txtapellidojugadores.setText("");
            txtsueldojugadores.setText("");
            txtpocision.setText("");
            txtestatura.setText("");
            txtpeso.setText("");

            mostrar();

        }

    }
    
    public void keyTyped(KeyEvent e) 

    {
    if (txtcedulajugadores.getText().length()== 15) 

         e.consume(); 
    } 

    public void mostrar() {
        String matriz[][] = new String[jugadores.size()][7];

        for (int i = 0; i < jugadores.size(); i++) {
            matriz[i][0] = Integer.toString(jugadores.get(i).getId());
            matriz[i][1] = jugadores.get(i).getNombre();
            matriz[i][2] = jugadores.get(i).getApellidos();
            matriz[i][3] = Double.toString(jugadores.get(i).getSueldo());
            matriz[i][4] = jugadores.get(i).getPocision();
            matriz[i][5] = Double.toString(jugadores.get(i).getEstatura());
            matriz[i][6] = Double.toString(jugadores.get(i).getPeso());
        }
        jTjugadores.setModel(new javax.swing.table.DefaultTableModel(
                matriz,
                new String[]{
                    "Cedula", "Nombre", "Apellido", "Sueldo", "Pocision", "Estatura", "Peso"
                }
        ));
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnregistrarjugadores;
    private javax.swing.JButton btnsalirjugadores;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTjugadores;
    private javax.swing.JLabel lblapellidojugadores;
    private javax.swing.JLabel lblcedulaJugadores;
    private javax.swing.JLabel lblestatura;
    private javax.swing.JLabel lblnombrejugadores;
    private javax.swing.JLabel lblpeso;
    private javax.swing.JLabel lblpocision;
    private javax.swing.JLabel lblsueldojugadores;
    private javax.swing.JTextField txtapellidojugadores;
    private javax.swing.JTextField txtcedulajugadores;
    private javax.swing.JTextField txtestatura;
    private javax.swing.JTextField txtnombrejugadores;
    private javax.swing.JTextField txtpeso;
    private javax.swing.JTextField txtpocision;
    private javax.swing.JTextField txtsueldojugadores;
    // End of variables declaration//GEN-END:variables
}
