/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Jugadores;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;

/**
 *
 * @author aldai
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("../Image/nantes.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jmplantilla = new javax.swing.JMenu();
        jmiJugadores = new javax.swing.JMenuItem();
        jmiEntrenadores = new javax.swing.JMenuItem();
        jmiAuxiliares = new javax.swing.JMenuItem();
        jmvaloracion = new javax.swing.JMenu();
        jmiValoracion = new javax.swing.JMenuItem();
        jmopciones = new javax.swing.JMenu();
        jmiSalir = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Equipo Libertadores");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/estadio.jpg"))); // NOI18N

        jmplantilla.setText("Registro de Plantilla");

        jmiJugadores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/jugador.png"))); // NOI18N
        jmiJugadores.setText("Registrar Jugadores");
        jmiJugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiJugadoresActionPerformed(evt);
            }
        });
        jmplantilla.add(jmiJugadores);

        jmiEntrenadores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/entrenador.png"))); // NOI18N
        jmiEntrenadores.setText("Registrar Entrenadores");
        jmplantilla.add(jmiEntrenadores);

        jmiAuxiliares.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/social-care.png"))); // NOI18N
        jmiAuxiliares.setText("Registrar Auxiliares");
        jmplantilla.add(jmiAuxiliares);

        jMenuBar2.add(jmplantilla);

        jmvaloracion.setText("Valoración Medica");

        jmiValoracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/doctor.png"))); // NOI18N
        jmiValoracion.setText("Registrar Valoración");
        jmvaloracion.add(jmiValoracion);

        jMenuBar2.add(jmvaloracion);

        jmopciones.setText("Opciones");

        jmiSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/off.png"))); // NOI18N
        jmiSalir.setText("Salir");
        jmiSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSalirActionPerformed(evt);
            }
        });
        jmopciones.add(jmiSalir);

        jMenuBar2.add(jmopciones);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jmiSalirActionPerformed

    private void jmiJugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiJugadoresActionPerformed
       frmJugadores jug = new frmJugadores();
       jug.setVisible(true);
    }//GEN-LAST:event_jmiJugadoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jmiAuxiliares;
    private javax.swing.JMenuItem jmiEntrenadores;
    private javax.swing.JMenuItem jmiJugadores;
    private javax.swing.JMenuItem jmiSalir;
    private javax.swing.JMenuItem jmiValoracion;
    private javax.swing.JMenu jmopciones;
    private javax.swing.JMenu jmplantilla;
    private javax.swing.JMenu jmvaloracion;
    // End of variables declaration//GEN-END:variables
}
